
[window]
dimensions = { columns = 102, lines = 30 }
padding = { x = 10, y = 10 }

decorations = "None"
title = "Fedora Workstation"
dynamic_title = false

[font]
normal = { family = "Monaspace Neon NF", style = "Regular" }

[general]
# Import the Catppuccin Macchiato theme
import = [
  "~/.config/alacritty/themes/catppuccin-macchiato.toml"
]
